apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailserver.fullname" . }}
  labels:
    app: {{ template "mailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mailserver.RSPAMD_PASSWORD }}
  mailserver-rspamd-password:  {{ .Values.mailserver.RSPAMD_PASSWORD | b64enc | quote }}
  {{ else }}
  mailserver-rspamd-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
