{{/*
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailserver.mariadb.fullname" . }}
  labels:
    app: {{ template "mailserver.mariadb.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mailserver.DBPASS }}
  mariadb-password:  {{ .Values.mailserver.DBPASS | b64enc | quote }}
  {{ else }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mailserver.DBROOT }}
  mariadb-root-password:  {{ .Values.mailserver.DBROOT | b64enc | quote }}
  {{ else }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
*/}}
