apiVersion: v1
kind: Service
metadata:
  name: {{ template "mailserver.postfixadmin.fullname" . }}
  labels:
    app: {{ template "mailserver.postfixadmin.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.postfixadmin.service.type }}
  ports:
  - name: postfixadmin
    protocol: TCP
    port: 8888
    targetPort: 8888
{{- if .Values.postfixadmin.service.nodePort }}
    nodePort: {{ .Values.postfixadmin.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "mailserver.postfixadmin.name" . }}
