{{- if .Values.postfixadmin.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "mailserver.postfixadmin.fullname" . }}-ingress
  labels:
    app: {{ template "mailserver.postfixadmin.fullname" . }}-ingress
  annotations:
    {{- if .Values.postfixadmin.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.postfixadmin.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: postfixadmin.{{ .Values.mailserver.MAILSERVER_DOMAIN }}
  #- host: {{ .Values.postfixadmin.ingress.host }}
    http:
      paths:
        - path: {{ default "/" .Values.postfixadmin.ingress.path }}
          backend:
            serviceName: {{ template "mailserver.postfixadmin.fullname" . }}
            servicePort: 8888
{{- if .Values.postfixadmin.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.postfixadmin.ingress.host }}
    secretName: {{ .Values.postfixadmin.ingress.tlsSecret }}
{{- end }}
{{- end }}
